"""Add icon_sprite_id and equipped_sprite_id to items

Revision ID: 9e1a169531d4
Revises: l7m8n9o0p1q2
Create Date: 2026-02-05 10:46:47.983846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1a169531d4'
down_revision: Union[str, None] = 'l7m8n9o0p1q2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('items', sa.Column('icon_sprite_id', sa.String(), nullable=True))
    op.add_column('items', sa.Column('equipped_sprite_id', sa.String(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE items SET icon_sprite_id = 'default_icon' WHERE icon_sprite_id IS NULL")
    op.execute("UPDATE items SET equipped_sprite_id = icon_sprite_id WHERE equipped_sprite_id IS NULL")
    
    # Make columns non-nullable
    op.alter_column('items', 'icon_sprite_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'equipped_sprite_id')
    op.drop_column('items', 'icon_sprite_id')
    # ### end Alembic commands ###
