"""Change map_id from integer to string

Revision ID: ab543bb48349
Revises: c59e100c5e5a
Create Date: 2025-09-16 15:38:25.882057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab543bb48349"
down_revision: Union[str, None] = "c59e100c5e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, add a new temporary column
    op.add_column("players", sa.Column("map_id_temp", sa.String(), nullable=True))

    # Migrate data from integer to string
    # Map integer values to string equivalents
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        UPDATE players 
        SET map_id_temp = CASE 
            WHEN map_id = 1 THEN 'test_map'
            ELSE 'test_map'
        END
    """
        )
    )

    # Drop the old column
    op.drop_column("players", "map_id")

    # Rename the temporary column to map_id
    op.alter_column("players", "map_id_temp", new_column_name="map_id")

    # Set default value and make it not nullable
    op.alter_column("players", "map_id", nullable=False, server_default="test_map")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add temporary integer column
    op.add_column("players", sa.Column("map_id_temp", sa.Integer(), nullable=True))

    # Migrate data from string back to integer
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        UPDATE players 
        SET map_id_temp = CASE 
            WHEN map_id = 'test_map' THEN 1
            ELSE 0
        END
    """
        )
    )

    # Drop the string column
    op.drop_column("players", "map_id")

    # Rename temporary column back to map_id
    op.alter_column("players", "map_id_temp", new_column_name="map_id")

    # Set default value and make it not nullable
    op.alter_column("players", "map_id", nullable=False, server_default="0")

    # ### end Alembic commands ###
