"""create entities table

Revision ID: f2f7f95b2638
Revises: h3c4d5e6f7g8
Create Date: 2026-01-30 15:34:52.245898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2f7f95b2638'
down_revision: Union[str, None] = 'h3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('behavior', sa.String(), nullable=False),
    sa.Column('is_attackable', sa.Boolean(), nullable=False),
    sa.Column('sprite_name', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('aggro_radius', sa.Integer(), nullable=False),
    sa.Column('respawn_time', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('dialogue', sa.JSON(), nullable=True),
    sa.Column('shop_id', sa.String(), nullable=True),
    sa.Column('attack_bonus', sa.Integer(), nullable=False),
    sa.Column('strength_bonus', sa.Integer(), nullable=False),
    sa.Column('ranged_attack_bonus', sa.Integer(), nullable=False),
    sa.Column('ranged_strength_bonus', sa.Integer(), nullable=False),
    sa.Column('magic_attack_bonus', sa.Integer(), nullable=False),
    sa.Column('magic_damage_bonus', sa.Integer(), nullable=False),
    sa.Column('physical_defence_bonus', sa.Integer(), nullable=False),
    sa.Column('magic_defence_bonus', sa.Integer(), nullable=False),
    sa.Column('speed_bonus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.alter_column('ground_items', 'dropped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'x_coord',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'y_coord',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'y_coord',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'x_coord',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ground_items', 'dropped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
